from tkinter import *
root=Tk()
root.geometry('450x650')
root.minsize(450,650)
root.maxsize(450,650)
root.title('CALCULATOR')
root.config(background='#F0F8FF')
scvalue=StringVar()
scvalue.set('')
screen=Entry(root,textvar=scvalue,font='lucida 35 bold')
screen.pack(fill=X,ipadx=8,pady=10,padx=10)
def click(event):
    global scvalue
    try:
        text=event.widget.cget('text')
        if text=='=':
            if scvalue.get().isdigit():
                value=int(scvalue.get())
            else:
                value=eval(screen.get())
            scvalue.set(value)
            screen.update()
        elif text=='C':
            scvalue.set('')
            screen.update()

        else:
            scvalue.set(scvalue.get()+text)
            screen.update()
    except:
        screen.delete(0,END)
        screen.insert(0,'MATH ERROR')
f=Frame(root,background='#98F5FF')
b=Button(f,text='9',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f,text='8',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f,text='7',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f,text='/',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
f.pack()
f1=Frame(root,background='#98F5FF')
b=Button(f1,text='6',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)

b=Button(f1,text='5',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)

b=Button(f1,text='4',padx=10,pady=1,font='comicsans 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f1,text='*',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=4,pady=4)
b.bind('<Button-1>',click)
f1.pack()
f2=Frame(root,background='#98F5FF')
b=Button(f2,text='3',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f2,text='2',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f2,text='1',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f2,text='-',padx=10,pady=2,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
f2.pack()
f3=Frame(root,background='#98F5FF')
b=Button(f3,text='0',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f3,text='%',padx=5,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=3,pady=3)
b.bind('<Button-1>',click)
b=Button(f3,text='.',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
b=Button(f3,text='+',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=5,pady=5)
b.bind('<Button-1>',click)
f3.pack()
f4=Frame(root,background='#98F5FF')
b=Button(f4,text='C',padx=10,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=3,pady=3)
b.bind('<Button-1>',click)
b=Button(f4,text='00',padx=1,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=1,pady=1)
b.bind('<Button-1>',click)
b=Button(f4,text='**',padx=1,pady=1,font='lucida 35 bold')
b.pack(side=LEFT,padx=3,pady=3)
b.bind('<Button-1>',click)
b=Button(f4,text='=',padx=10,pady=1,font='comicsans 35 bold')
b.pack(side=LEFT,padx=3,pady=3)
b.bind('<Button-1>',click)
f4.pack()
f5=Frame(root,background='grey')


f5.pack()
root.mainloop()